import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import { resolve, extname } from "node:path";

// Adds a fitting-room model from a model sheet image:
//
//   node scripts/add-model.mjs <image> <id> "<NAME>" "<detail>" "<identity prompt>"
//   e.g. node scripts/add-model.mjs ~/sheets/maya.webp maya "MAYA CHEN" "5'9\" · Columbus, Ohio" \
//        "Preserve her recognizable face, light tan skin tone, straight black bob, adult age, and identity."
//
// It copies the image to public/models/<id>.<ext> (used by the studio picker
// and the offline style board), embeds a base64 copy in src/model-sheets/<id>.js
// (used server-side by /api/try-on), and registers the model in src/models.js
// and src/model-sheets.js via their insertion markers.

const [, , imagePath, id, name, detail = "", identity = ""] = process.argv;
if (!imagePath || !id || !name) {
  console.error('Usage: node scripts/add-model.mjs <image> <id> "<NAME>" "<detail>" "<identity prompt>"');
  process.exit(1);
}
if (!/^[a-z][a-z0-9-]*$/.test(id)) {
  console.error(`The id "${id}" must be lowercase letters, digits, or dashes (e.g. "maya").`);
  process.exit(1);
}

const extension = extname(imagePath).toLowerCase();
const mime = { ".webp": "image/webp", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg" }[extension];
if (!mime) {
  console.error(`Unsupported image type "${extension}" — use .webp, .png, or .jpg.`);
  process.exit(1);
}

const file = await readFile(resolve(imagePath));
if (file.length > 4_000_000) {
  console.error("The model sheet is over 4 MB — export it smaller (a ~1200px-tall webp is ideal) and rerun.");
  process.exit(1);
}

await mkdir(resolve("public/models"), { recursive: true });
const publicPath = `public/models/${id}${extension}`;
await copyFile(resolve(imagePath), resolve(publicPath));

await mkdir(resolve("src/model-sheets"), { recursive: true });
const constName = `${id.replace(/-/g, "_").toUpperCase()}_SHEET`;
await writeFile(
  resolve(`src/model-sheets/${id}.js`),
  `// Generated by scripts/add-model.mjs — model sheet for "${id}".\nexport const MODEL_IMAGE = "data:${mime};base64,${file.toString("base64")}";\n`,
);

// Register in src/model-sheets.js.
const sheetsPath = resolve("src/model-sheets.js");
let sheets = await readFile(sheetsPath, "utf8");
if (!sheets.includes(`"./model-sheets/${id}.js"`)) {
  sheets = sheets
    .replace(/^(\/\/ \[add-model:imports\].*)$/m, `import { MODEL_IMAGE as ${constName} } from "./model-sheets/${id}.js";\n$1`)
    .replace(/^(\s*)(\/\/ \[add-model:sheets\].*)$/m, `$1${id.includes("-") ? `"${id}"` : id}: ${constName},\n$1$2`);
  await writeFile(sheetsPath, sheets);
}

// Register in src/models.js.
const modelsPath = resolve("src/models.js");
let models = await readFile(modelsPath, "utf8");
if (!models.includes(`id: "${id}"`)) {
  const count = (models.match(/\bid: "/g) || []).length + 1;
  const entry = [
    "  {",
    `    id: "${id}",`,
    `    code: "MODEL ${String(count).padStart(3, "0")}",`,
    `    name: ${JSON.stringify(name)},`,
    `    detail: ${JSON.stringify(detail)},`,
    `    image: "/models/${id}${extension}",`,
    `    identity:\n      ${JSON.stringify(identity || "Preserve this model's recognizable face, skin tone, hair, adult age, proportions, and identity exactly as shown in the reference sheet.")},`,
    "  },",
  ].join("\n");
  models = models.replace(/^\];$/m, `${entry}\n];`);
  await writeFile(modelsPath, models);
}

console.log(`Model "${id}" added:`);
console.log(`  • ${publicPath} (studio picker + style board)`);
console.log(`  • src/model-sheets/${id}.js (server-side sheet for /api/try-on)`);
console.log("  • registered in src/models.js and src/model-sheets.js");
console.log("Review the generated entry in src/models.js (name, detail, identity prompt), then build.");
